In [1]:
import pandas as pd

In [2]:
sales = pd.read_csv('sales.csv')

In [3]:
sales.head()

      Product     Category  Price  Quantity
0       Phone  Electronics  60000        10
1      Laptop  Electronics  80000         5
2     Monitor  Electronics  12500         8
3      Tablet  Electronics  35000         6
4  Smartwatch  Electronics   8500        15

In [4]:
sales['GST_percent'] = 18

In [5]:
sales.head()

      Product     Category  Price  Quantity  GST_percent
0       Phone  Electronics  60000        10           18
1      Laptop  Electronics  80000         5           18
2     Monitor  Electronics  12500         8           18
3      Tablet  Electronics  35000         6           18
4  Smartwatch  Electronics   8500        15           18

In [6]:
sales.drop(columns = ['Phone'])

KeyError: "['Phone'] not found in axis"

In [ ]:
gst = {
    'Electronics': 18,
    'Accessories': 5,
    'Stationery' : 0,
    'Furniture' : 15
}

sales['GST_percentage'] = sales['Category'].map(gst)

In [ ]:
sales

,Product,Category,Price,Quantity,Phone,GST_percent,GST_percentage
0,Phone,Electronics,60000,10,75999,18,18
1,Laptop,Electronics,80000,5,75999,18,18
2,Monitor,Electronics,12500,8,75999,18,18
3,Tablet,Electronics,35000,6,75999,18,18
4,Smartwatch,Electronics,8500,15,75999,18,18
5,Mouse,Accessories,1500,50,75999,18,5
6,Keyboard,Accessories,2500,20,75999,18,5
7,USB Cable,Accessories,300,100,75999,18,5
8,Headphones,Accessories,2000,30,75999,18,5
9,Webcam,Accessories,3500,12,75999,18,5
10,Notebook,Stationery,50,200,75999,18,0
11,Pen,Stationery,10,500,75999,18,0
12,Stapler,Stationery,150,40,75999,18,0
13,Desk Lamp,Furniture,1200,25,75999,18,15
14,Office Chair,Furniture,7000,10,75999,18,15

In [ ]:
sales.drop(columns = ['Phone'], inplace = True)

In [ ]:
sales

         Product     Category  Price  Quantity  GST_percent  GST_percentage
0          Phone  Electronics  60000        10           18              18
1         Laptop  Electronics  80000         5           18              18
2        Monitor  Electronics  12500         8           18              18
3         Tablet  Electronics  35000         6           18              18
4     Smartwatch  Electronics   8500        15           18              18
5          Mouse  Accessories   1500        50           18               5
6       Keyboard  Accessories   2500        20           18               5
7      USB Cable  Accessories    300       100           18               5
8     Headphones  Accessories   2000        30           18               5
9         Webcam  Accessories   3500        12           18               5
10      Notebook   Stationery     50       200           18               0
11           Pen   Stationery     10       500           18               0
12       Stapler   Stationery    150        40           18               0
13     Desk Lamp    Furniture   1200        25           18              15
14  Office Chair    Furniture   7000        10           18              15

In [ ]:
sales.drop(columns = ['GST_percent'], inplace = True)

In [ ]:
sales

         Product     Category  Price  Quantity  GST_percentage
0          Phone  Electronics  60000        10              18
1         Laptop  Electronics  80000         5              18
2        Monitor  Electronics  12500         8              18
3         Tablet  Electronics  35000         6              18
4     Smartwatch  Electronics   8500        15              18
5          Mouse  Accessories   1500        50               5
6       Keyboard  Accessories   2500        20               5
7      USB Cable  Accessories    300       100               5
8     Headphones  Accessories   2000        30               5
9         Webcam  Accessories   3500        12               5
10      Notebook   Stationery     50       200               0
11           Pen   Stationery     10       500               0
12       Stapler   Stationery    150        40               0
13     Desk Lamp    Furniture   1200        25              15
14  Office Chair    Furniture   7000        10              15