In [1]:
import pandas as pd

In [2]:
bios = pd.read_csv('athlete_events.csv')

In [ ]:
bios.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN

In [ ]:
bios.loc[1:15]

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN
5,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,"Speed Skating Women's 1,000 metres",NaN
6,5,Christine Jacoba Aaftink,F,25.0,185.0,82.0,Netherlands,NED,1992 Winter,1992,Winter,Albertville,Speed Skating,Speed Skating Women's 500 metres,NaN
7,5,Christine Jacoba Aaftink,F,25.0,185.0,82.0,Netherlands,NED,1992 Winter,1992,Winter,Albertville,Speed Skating,"Speed Skating Women's 1,000 metres",NaN
8,5,Christine Jacoba Aaftink,F,27.0,185.0,82.0,Netherlands,NED,1994 Winter,1994,Winter,Lillehammer,Speed Skating,Speed Skating Women's 500 metres,NaN
9,5,Christine Jacoba Aaftink,F,27.0,185.0,82.0,Netherlands,NED,1994 Winter,1994,Winter,Lillehammer,Speed Skating,"Speed Skating Women's 1,000 metres",NaN
10,6,Per Knut Aaland,M,31.0,188.0,75.0,United States,USA,1992 Winter,1992,Winter,Albertville,Cross Country Skiing,Cross Country Skiing Men's 10 kilometres,NaN
11,6,Per Knut Aaland,M,31.0,188.0,75.0,United States,USA,1992 Winter,1992,Winter,Albertville,Cross Country Skiing,Cross Country Skiing Men's 50 kilometres,NaN
12,6,Per Knut Aaland,M,31.0,188.0,75.0,United States,USA,1992 Winter,1992,Winter,Albertville,Cross Country Skiing,Cross Country Skiing Men's 10/15 kilometres Pu...,NaN
13,6,Per Knut Aaland,M,31.0,188.0,75.0,United States,USA,1992 Winter,1992,Winter,Albertville,Cross Country Skiing,Cross Country Skiing Men's 4 x 10 kilometres R...,NaN
14,6,Per Knut Aaland,M,33.0,188.0,75.0,United States,USA,1994 Winter,1994,Winter,Lillehammer,Cross Country Skiing,Cross Country Skiing Men's 10 kilometres,NaN
15,6,Per Knut Aaland,M,33.0,188.0,75.0,United States,USA,1994 Winter,1994,Winter,Lillehammer,Cross Country Skiing,Cross Country Skiing Men's 30 kilometres,NaN

In [ ]:
bios.iloc[0:5,[0,3]]

   ID   Age
0   1  24.0
1   2  23.0
2   3  24.0
3   4  34.0
4   5  21.0

In [ ]:
bios.loc[bios['Height'] > 215,['Name','Height','Weight']]

                                                     Name  Height  Weight
14132                                         Stanko Bara   217.0   110.0
17669                                      Gunther Behnke   221.0   114.0
22743                                            Uwe Blab   218.0   110.0
22744                                            Uwe Blab   218.0   110.0
32376                                Tommy Loren Burleson   223.0   102.0
34307                              Andrew "Andy" Campbell   218.0    93.0
34308                              Andrew "Andy" Campbell   218.0    93.0
38381                              Tyson Cleotis Chandler   216.0   107.0
47982                                 Paulo Csar da Silva   217.0   106.0
59371                              Roberto Dueas Hernndez   221.0   137.0
59372                              Roberto Dueas Hernndez   221.0   137.0
80447                                 Andreas Glyniadakis   216.0   115.0
87972                                    Hamed E. Haddadi   218.0   110.0
90309                                         Lars Hansen   216.0   105.0
99965                                         Hu Zhangbao   216.0   135.0
115016                        Aleksey Valeryevich Kazakov   217.0   102.0
115017                        Aleksey Valeryevich Kazakov   217.0   102.0
115018                        Aleksey Valeryevich Kazakov   217.0   102.0
125769                         Serhiy Ivanovych Kovalenko   216.0   111.0
125770                         Serhiy Ivanovych Kovalenko   216.0   111.0
127690                                          Jnis Krmi   218.0   141.0
127691                                          Jnis Krmi   218.0   141.0
127692                                          Jnis Krmi   218.0   141.0
138228                                           Li Muhao   218.0   115.0
141983                         Lucien James "Luc" Longley   220.0   135.0
141984                         Lucien James "Luc" Longley   220.0   135.0
141985                         Lucien James "Luc" Longley   220.0   135.0
156025                                     Salah Al-Mejri   216.0   110.0
164743                           Timofey Pavlovich Mozgov   216.0   113.0
166544                     Dmitry Aleksandrovich Musersky   219.0   104.0
177224                           Shaquille Rashuan O'Neal   216.0   137.0
181241                  Viktor Aleksandrovich Pankrashkin   220.0   112.0
183420  Paulo "Paulinho Villas Boas" Villas de Almeida...   217.0   106.0
183421  Paulo "Paulinho Villas Boas" Villas de Almeida...   217.0   106.0
196667                           Peter John Ramos Fuentes   219.0   113.0
201955                             David Maurice Robinson   216.0   107.0
201956                             David Maurice Robinson   216.0   107.0
201957                             David Maurice Robinson   216.0   107.0
207373                              Arvydas Romas Sabonis   223.0   122.0
207374                              Arvydas Romas Sabonis   223.0   122.0
207375                              Arvydas Romas Sabonis   223.0   122.0
240656                      Volodymyr Petrovych Tkachenko   220.0   110.0
240657                      Volodymyr Petrovych Tkachenko   220.0   110.0
254915                           Stojan "Stojko" Vrankovi   217.0   115.0
254916                           Stojan "Stojko" Vrankovi   217.0   115.0
254917                           Stojan "Stojko" Vrankovi   217.0   115.0
258453                             Frdric Jean Santo Weis   218.0   110.0
265040                                           Yao Ming   226.0   141.0
265041                                           Yao Ming   226.0   141.0
265042                                           Yao Ming   226.0   141.0
269053                                       Zhang Zhaoxu   221.0   110.0
269409                                            Zhou Qi   217.0    95.0
270740                                 Eurelijus ukauskas   218.0   115.0
270741                                 Eurelijus ukauskas   218.0   115.0
270742                                 Eurelijus ukauskas   218.0   115.0

In [ ]:
bios[(bios['Height'] > 200)]

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
299,161,Hossam Abdalla,M,28.0,203.0,97.0,Egypt,EGY,2016 Summer,2016,Summer,Rio de Janeiro,Volleyball,Volleyball Men's Volleyball,NaN
443,246,Mamdouh Abdelrehim,M,26.0,207.0,90.0,Egypt,EGY,2016 Summer,2016,Summer,Rio de Janeiro,Volleyball,Volleyball Men's Volleyball,NaN
609,351,Julius Shareef Abdur-Rahim,M,23.0,202.0,104.0,United States,USA,2000 Summer,2000,Summer,Sydney,Basketball,Basketball Men's Basketball,Gold
820,468,Abdelhalim Muhammad Abou,M,27.0,210.0,88.0,Egypt,EGY,2016 Summer,2016,Summer,Rio de Janeiro,Volleyball,Volleyball Men's Volleyball,NaN
833,474,Essameldin Abou El-Nein,M,29.0,205.0,102.0,Egypt,EGY,1984 Summer,1984,Summer,Los Angeles,Basketball,Basketball Men's Basketball,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
270741,135401,Eurelijus ukauskas,M,27.0,218.0,115.0,Lithuania,LTU,2000 Summer,2000,Summer,Sydney,Basketball,Basketball Men's Basketball,Bronze
270742,135401,Eurelijus ukauskas,M,30.0,218.0,115.0,Lithuania,LTU,2004 Summer,2004,Summer,Athina,Basketball,Basketball Men's Basketball,NaN
270743,135402,Mindaugas ukauskas,M,20.0,201.0,100.0,Lithuania,LTU,1996 Summer,1996,Summer,Atlanta,Basketball,Basketball Men's Basketball,Bronze
270744,135402,Mindaugas ukauskas,M,28.0,201.0,100.0,Lithuania,LTU,2004 Summer,2004,Summer,Athina,Basketball,Basketball Men's Basketball,NaN
271026,135530,Philip Zwiener,M,23.0,202.0,98.0,Germany,GER,2008 Summer,2008,Summer,Beijing,Basketball,Basketball Men's Basketball,NaN

In [ ]:
bios[(bios['Weight'] > 75) & (bios['Event'] == "Basketball Men's Basketball")]

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
264,136,Alessandro Abbio,M,29.0,195.0,85.0,Italy,ITA,2000 Summer,2000,Summer,Sydney,Basketball,Basketball Men's Basketball,NaN
346,192,Ahmed El-Sayed Abdel Hamid Mobarak,M,25.0,189.0,85.0,Egypt,EGY,1972 Summer,1972,Summer,Munich,Basketball,Basketball Men's Basketball,NaN
363,202,Awad Abdel Nabi Awad,M,19.0,198.0,80.0,Egypt,EGY,1972 Summer,1972,Summer,Munich,Basketball,Basketball Men's Basketball,NaN
364,202,Awad Abdel Nabi Awad,M,23.0,198.0,80.0,Egypt,EGY,1976 Summer,1976,Summer,Montreal,Basketball,Basketball Men's Basketball,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
270741,135401,Eurelijus ukauskas,M,27.0,218.0,115.0,Lithuania,LTU,2000 Summer,2000,Summer,Sydney,Basketball,Basketball Men's Basketball,Bronze
270742,135401,Eurelijus ukauskas,M,30.0,218.0,115.0,Lithuania,LTU,2004 Summer,2004,Summer,Athina,Basketball,Basketball Men's Basketball,NaN
270743,135402,Mindaugas ukauskas,M,20.0,201.0,100.0,Lithuania,LTU,1996 Summer,1996,Summer,Atlanta,Basketball,Basketball Men's Basketball,Bronze
270744,135402,Mindaugas ukauskas,M,28.0,201.0,100.0,Lithuania,LTU,2004 Summer,2004,Summer,Athina,Basketball,Basketball Men's Basketball,NaN
271026,135530,Philip Zwiener,M,23.0,202.0,98.0,Germany,GER,2008 Summer,2008,Summer,Beijing,Basketball,Basketball Men's Basketball,NaN

In [ ]:
bios[bios['City'].isin(["USA"])]

Empty DataFrame
Columns: [ID, Name, Sex, Age, Height, Weight, Team, NOC, Games, Year, Season, City, Sport, Event, Medal]
Index: []

In [3]:
bios_new = bios.copy()

In [4]:
bios_new.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN

In [5]:
bios_new["first_name"] = bios_new['Name'].str.split(" ").str[0]

In [6]:
bios_new.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal,first_name
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN,A
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN,A
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN,Gunnar
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold,Edgar
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN,Christine